# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import (
    Optional,
    Union,
)


def round_edge_grill(
    alpha: float,
    l: Optional[float] = ...,
    Dh: Optional[float] = ...,
    fd: Optional[float] = ...
) -> float: ...


def round_edge_open_mesh(alpha: float, subtype: str = ..., angle: float = ...) -> float: ...


def round_edge_screen(alpha: float, Re: int, angle: int = ...) -> float: ...


def square_edge_grill(
    alpha: float,
    l: Optional[float] = ...,
    Dh: Optional[float] = ...,
    fd: Optional[float] = ...
) -> float: ...


def square_edge_screen(alpha: float) -> float: ...

__all__: List[str]