# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from __future__ import annotations
from typing import List
from typing import (
    Optional,
)


def liquid_jet_pump_ancillary(
    rhop: float,
    rhos: float,
    Kp: float,
    Ks: float,
    d_nozzle: Optional[float] = ...,
    d_mixing: Optional[float] = ...,
    Qp: Optional[float] = ...,
    Qs: Optional[float] = ...,
    P1: Optional[float] = ...,
    P2: Optional[int] = ...
) -> float: ...


def vacuum_air_leakage_Coker_Worthington(P: float, P_atm: float = ..., conservative: bool = ...) -> float: ...


def vacuum_air_leakage_HEI2633(V: float, P: float, P_atm: float = ...) -> float: ...


def vacuum_air_leakage_Ryans_Croll(V: int, P: int, P_atm: float = ...) -> float: ...


def vacuum_air_leakage_Seider(V: int, P: int, P_atm: float = ...) -> float: ...

__all__: List[str]