# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from __future__ import annotations
from typing import List
from typing import Optional


def liquid_jet_pump_ancillary(
    rhop: float,
    rhos: float,
    Kp: float,
    Ks: float,
    d_nozzle: Optional[float] = ...,
    d_mixing: Optional[float] = ...,
    Qp: Optional[float] = ...,
    Qs: Optional[float] = ...,
    P1: Optional[float] = ...,
    P2: Optional[int] = ...
) -> float: ...

__all__: List[str]