# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import (
    Optional,
    Union,
)


def COV_motionless_mixer(Ki: float, Q1: float, Q2: float, pipe_diameters: float) -> float: ...


def K_motionless_mixer(K: int, L: float, D: float, fd: float) -> float: ...


def Kp_helical_ribbon_Rieger(D: float, h: float, nb: int, pitch: float, width: float, T: int) -> float: ...


def adjust_homogeneity(fraction: float) -> float: ...


def agitator_time_homogeneous(
    N: float,
    P: float,
    T: float,
    H: float,
    mu: float,
    rho: int,
    D: Optional[float] = ...,
    homogeneity: float = ...
) -> float: ...


def size_tee(Q1: float, Q2: float, D: float, D2: None, n: int = ..., pipe_diameters: int = ...) -> float: ...


def time_helical_ribbon_Grenville(Kp: float, N: float) -> float: ...

__all__: List[str]