# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import Union


def C_Chezy_to_n_Manning(C: float, Rh: int) -> float: ...


def Q_weir_V_Shen(h1: float, angle: int = ...) -> float: ...


def Q_weir_rectangular_Kindsvater_Carter(h1: float, h2: float, b: int) -> float: ...


def Q_weir_rectangular_SIA(h1: float, h2: float, b: int, b1: int) -> float: ...


def Q_weir_rectangular_full_Ackers(h1: float, h2: float, b: int) -> float: ...


def Q_weir_rectangular_full_Kindsvater_Carter(h1: float, h2: float, b: int) -> float: ...


def Q_weir_rectangular_full_Rehbock(h1: float, h2: float, b: int) -> float: ...


def Q_weir_rectangular_full_SIA(h1: float, h2: float, b: int) -> float: ...


def V_Chezy(Rh: int, S: float, C: float) -> float: ...


def V_Manning(Rh: float, S: float, n: float) -> float: ...


def n_Manning_to_C_Chezy(n: float, Rh: int) -> float: ...

__all__: List[str]