# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from __future__ import annotations
from typing import List


def C_Chezy_to_n_Manning(C: float, Rh: float) -> float: ...


def Q_weir_V_Shen(h1: float, angle: int = ...) -> float: ...


def Q_weir_rectangular_Kindsvater_Carter(h1: float, h2: float, b: float) -> float: ...


def Q_weir_rectangular_SIA(h1: float, h2: float, b: float, b1: float) -> float: ...


def Q_weir_rectangular_full_Ackers(h1: float, h2: float, b: float) -> float: ...


def Q_weir_rectangular_full_Kindsvater_Carter(h1: float, h2: float, b: float) -> float: ...


def Q_weir_rectangular_full_Rehbock(h1: float, h2: float, b: float) -> float: ...


def Q_weir_rectangular_full_SIA(h1: float, h2: float, b: float) -> float: ...


def V_Chezy(Rh: float, S: float, C: float) -> float: ...


def V_Manning(Rh: float, S: float, n: float) -> float: ...


def n_Manning_to_C_Chezy(n: float, Rh: float) -> float: ...

__all__: List[str]