# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from __future__ import annotations
from typing import List
from typing import (
    List,
    Tuple,
)


def Robbins(L: float, G: float, rhol: float, rhog: float, mul: float, H: float = ..., Fpd: float = ...) -> float: ...


def Stichlmair_dry(
    Vg: float,
    rhog: float,
    mug: float,
    voidage: float,
    specific_area: float,
    C1: float,
    C2: float,
    C3: float,
    H: float = ...
) -> float: ...


def Stichlmair_flood(
    Vl: float,
    rhog: float,
    rhol: float,
    mug: float,
    voidage: float,
    specific_area: float,
    C1: float,
    C2: float,
    C3: float,
    H: float = ...
) -> float: ...


def Stichlmair_wet(
    Vg: float,
    Vl: float,
    rhog: float,
    rhol: float,
    mug: float,
    voidage: float,
    specific_area: float,
    C1: float,
    C2: float,
    C3: float,
    H: float = ...
) -> float: ...


def _Stichlmair_flood_f_and_jac(
    inputs: List[float],
    Vl: float,
    rhog: float,
    rhol: float,
    mug: float,
    voidage: float,
    specific_area: float,
    C1: float,
    C2: float,
    C3: float,
    H: float
) -> Tuple[List[float], List[List[float]]]: ...


def _Stichlmair_wet_err(dP_irr: float, h0: float, c1: float, dP_dry: float, H: float, voidage: float, c: float) -> float: ...


def dP_demister_dry_Setekleiv_Svendsen(
    S: float,
    voidage: float,
    vs: float,
    rho: float,
    mu: float,
    L: float = ...
) -> float: ...


def dP_demister_dry_Setekleiv_Svendsen_lit(
    S: float,
    voidage: float,
    vs: float,
    rho: float,
    mu: float,
    L: float = ...
) -> float: ...


def dP_demister_wet_ElDessouky(vs: float, voidage: float, d_wire: float, L: float = ...) -> float: ...


def separation_demister_ElDessouky(vs: float, voidage: float, d_wire: float, d_drop: float) -> float: ...


def specific_area_mesh(voidage: float, d: float) -> float: ...


def voidage_experimental(m: float, rho: float, D: float, H: float) -> float: ...

__all__: List[str]