# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from __future__ import annotations
from typing import List
from typing import (
    Optional,
    Tuple,
    Union,
)


def gauge_from_t(t: float, SI: bool = ..., schedule: str = ...) -> float: ...


def nearest_pipe(
    Do: Optional[float] = ...,
    Di: Optional[float] = ...,
    NPS: Optional[int] = ...,
    schedule: Union[int, str, float] = ...
) -> Tuple[int, float, float, float]: ...


def t_from_gauge(gauge: float, SI: bool = ..., schedule: str = ...) -> float: ...

__all__: List[str]