# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from numpy import float64
from typing import (
    Any,
    Optional,
    Union,
)


def CSA_motor_efficiency(P: float, closed: bool = ..., poles: int = ..., high_efficiency: bool = ...) -> float: ...


def Corripio_motor_efficiency(P: float) -> float: ...


def Corripio_pump_efficiency(Q: float) -> float: ...


def VFD_efficiency(P: float, load: float = ...) -> float64: ...


def current_ideal(P: float, V: int, phase: int = ..., PF: float = ...) -> float: ...


def motor_efficiency_underloaded(P: float, load: float = ...) -> float: ...


def motor_round_size(P: float) -> float: ...


def specific_diameter(Q: float, H: float, D: float) -> float: ...


def specific_speed(Q: float, H: int, n: int = ...) -> float: ...


def speed_synchronous(f: int, poles: int = ..., phase: int = ...) -> float: ...


class CountryPower:
    def __init__(self, country: str, voltage: Any, freq: int, plugs: Optional[Any] = ...) -> None: ...

__all__: List[str]