# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from __future__ import annotations
from typing import List
def Geldart_Ling(mp: float, rhog: float, D: float, mug: float) -> float: ...


def Matsumoto_1974(mp: float, rhop: float, dp: float, rhog: float, D: float, Vterminal: float = ...) -> float: ...


def Matsumoto_1975(mp: float, rhop: float, dp: float, rhog: float, D: float, Vterminal: float = ...) -> float: ...


def Matsumoto_1977(mp: float, rhop: float, dp: float, rhog: float, D: float, Vterminal: float = ...) -> float: ...


def Rizk(mp: float, dp: float, rhog: float, D: float) -> float: ...


def Schade(mp: float, rhop: float, dp: float, rhog: float, D: float) -> float: ...


def Weber_saltation(mp: float, rhop: float, dp: float, rhog: float, D: float, Vterminal: float = ...) -> float: ...

__all__: List[str]