# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from __future__ import annotations
from typing import List
def K_Souders_Brown_theoretical(D: float, Cd: float, g: float = ...) -> float: ...


def K_separator_Watkins(x: float, rhol: float, rhog: float, horizontal: bool = ..., method: str = ...) -> float: ...


def K_separator_demister_York(P: float, horizontal: bool = ...) -> float: ...


def v_Souders_Brown(K: float, rhol: float, rhog: float) -> float: ...


K_Sounders_Brown_theoretical = K_Souders_Brown_theoretical
v_Sounders_Brown = v_Souders_Brown

__all__: List[str]