name: Build Multiarch

on:
  push:
    branches: [master, release, multi_arch_test]
  pull_request:
    branches: [master, release]

jobs:
  multi-arch-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [armv7, aarch64, riscv64, s390x, ppc64le]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Run on ${{ matrix.arch }}
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          install: |
            apt-get update
            apt-get install -y libopenblas-dev libatlas-base-dev liblapack-dev gfortran libgmp-dev libmpfr-dev libsuitesparse-dev ccache libmpc-dev python3 python3-pip
          run: |
            python3 -m pip install wheel --break-system-packages
            pip3 install -r requirements_test.txt --break-system-packages
            pytest . -v -m "not online and not thermo"