name: Publish to TestPyPI
on:
  push:
    tags:
      - 'v*'
permissions:
  id-token: write
  contents: read
jobs:
  test:
    uses: ./.github/workflows/quality.yml
  
  publish:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    environment:
      name: pypi
    steps:      
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: distributions
          path: dist/
      
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/        