name: Test Distribution

on:
  push:
    branches: [master, release]
  pull_request:
    branches: [master, release]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/release' }}

jobs:
  test-distributions:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Build distributions
      run: python -m build

    - name: Check distributions with twine
      run: twine check dist/*

    - name: Upload distributions as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: distributions
        path: dist/

    - name: Test wheel installation
      run: |
        python -m venv /tmp/wheel_test_env
        /tmp/wheel_test_env/bin/pip install dist/*.whl
        /tmp/wheel_test_env/bin/pip install pytest
        cd /tmp
        /tmp/wheel_test_env/bin/pytest --pyargs fluids -vv -m "not online and not thermo and not numba"

    - name: Test sdist installation
      run: |
        python -m venv /tmp/sdist_test_env
        /tmp/sdist_test_env/bin/pip install dist/*.tar.gz
        /tmp/sdist_test_env/bin/pip install pytest
        cd /tmp
        /tmp/sdist_test_env/bin/pytest --pyargs fluids -vv -m "not online and not thermo and not numba"
