name: Test Distribution

on:
  push:
    branches: [master, release]
  pull_request:
    branches: [master, release]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/release' }}

jobs:
  test-distributions:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Build distributions
      run: python -m build

    - name: Check distributions with twine
      run: twine check dist/*

    - name: Upload distributions as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: distributions
        path: dist/

    - name: Test wheel installation
      run: |
        WHEEL_TEST_DIR=$(mktemp -d)
        cd $WHEEL_TEST_DIR
        python -m venv venv
        WHEEL_FILE=$(ls $GITHUB_WORKSPACE/dist/*.whl)
        venv/bin/pip install "fluids[test] @ file://${WHEEL_FILE}"
        cp -r $GITHUB_WORKSPACE/tests .
        cp $GITHUB_WORKSPACE/pyproject.toml .
        venv/bin/pytest tests/ -vv -m "not online and not thermo and not numba"

    - name: Test sdist installation
      run: |
        SDIST_TEST_DIR=$(mktemp -d)
        cd $SDIST_TEST_DIR
        python -m venv venv
        SDIST_FILE=$(ls $GITHUB_WORKSPACE/dist/*.tar.gz)
        venv/bin/pip install "fluids[test] @ file://${SDIST_FILE}"
        cp -r $GITHUB_WORKSPACE/tests .
        cp $GITHUB_WORKSPACE/pyproject.toml .
        venv/bin/pytest tests/ -vv -m "not online and not thermo and not numba"
